spring.application.name=voyager
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/voyager}

spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.docker.compose.enabled=false
jwt.secret=${JWT_SECRET:thisIsMySuperSecretJwtKeyForVoyagerApplication2026SpringBootSecurity}
jwt.expiration=${JWT_EXPIRATION:3600000}
spring.ai.google.genai.api-key=${GEMINI_API_KEY:mock-gemini-key}
spring.ai.google.genai.chat.options.model=gemini-flash-latest
weather.api.key=${WEATHER_API_KEY:}
google.places.api-key=${GOOGLE_PLACES_API_KEY:}
logging.level.org.springframework.security=TRACE